version: 2
branches:
  only:
    - master
jobs:
  build:
    docker:
      - image: node:9.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-library-{{ checksum "yarn.lock" }}
            - yarn-library
      - run:
          name: Install libraries
          command: yarn install
      - save_cache:
          key: yarn-library-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Commit built README
          environment:
            TARGET: index.html
          command: |
            yarn run build
            git config user.email "a.d.xvii.kal.mai@gmail.com"
            git config user.name "TANIGUCHI Kohei"
            git add $TARGET
            git commit $TARGET -m "[ci skip] Update $TARGET by CircleCI" || true
            git push git@github.com:cohei/search-in-longman.git master
