version: 2
branches:
  only:
    - master
jobs:
  build:
    working_directory: /search-in-longman
    docker:
      - image: node:7.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-library-{{ checksum "yarn.lock" }}
            - yarn-library
      - run:
          name: Install libraries
          command: yarn install
      - save_cache:
          key: yarn-library-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Commit built README
          command: |
            yarn run build
            git config user.email "a.d.xvii.kal.mai@gmail.com"
            git config user.name "TANIGUCHI Kohei"
            if git commit README.md -m "[ci skip] Update README.md by CircleCI"; then
              git push git@github.com:cohei/search-in-longman.git mastera
            fi
